version: '3.8'

services:

  api:
  #Vai puxar no nosso dockerfile, já que estamos na mesma hierarquia de arquivos usamos o ponto
    build: .
    ports:
      - 8080:8080
    environment:
    #Vamos passar as variaveis pelo arquivo env
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST}
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT}
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}

    networks:
      - journey
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: api-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
    
    networks:
      - journey

networks:
  #nome da rede
  journey:
    driver: bridge
